# Generated by Django 3.2 on 2021-04-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='property_types',
            new_name='propertyTypes',
        ),
    ]
